### ISSUE TITLE
padronA5 button afip crash when try to get tipoDomicilio

### ISSUE THREAD

**Issue by lukio** [tryton-ar/party_ar#17]
``` Python
Traceback (most recent call last):
  File "/opt/trytond/trytond_dist/trytond/protocols/dispatcher.py", line 201, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/opt/trytond/trytond_dist/trytond/wizard/wizard.py", line 275, in execute
    return wizard._execute(state_name)
  File "/opt/trytond/trytond_dist/trytond/wizard/wizard.py", line 287, in _execute
    view['fields'].keys())
  File "/opt/trytond/trytond_dist/trytond/wizard/wizard.py", line 93, in get_defaults
    defaults.update(default(fields))
  File "/opt/trytond/trytond_dist/trytond/modules/party_ar/party.py", line 744, in default_start
    if domicilio.get('tipoDomicilio') == 'FISCAL':
AttributeError: 'list' object has no attribute 'get'

```

**Comment by lukio** [comment]
fixes related to #16
