### ISSUE TITLE
Cant install it..

### ISSUE THREAD

**Issue by s4msagaz** [tryton-ar/party_ar#2]
Error that i get when try to enable the module from Tryton Client

14279 139690265552640 [2016-10-08 09:43:53,110] ERROR trytond.protocols.dispatcher <class 'trytond.ir.module.ir.module.install_upgrade'>.execute(_(22, {u'start': {u'module_info': u'party_ar: to install', u'id': -48}}, u'upgrade', {u'date_format': u'%m/%d/%Y', u'language': u'en_US', u'locale': {u'date': u'%m/%d/%Y', u'thousands_sep': u',', u'decimal_point': u'.', u'grouping': [3, 3, 0]}, u'language_direction': u'ltr', u'company.rec_name': u'Jose Luis Zanotti', u'active_model': u'ir.module', u'groups': [4, 5, 1, 2, 3, 6], u'action_id': 42, u'employee': None, u'active_ids': [15], u'company': 1, u'active_id': 15}), *_{}) from admin@192.168.0.202//tryton/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/protocols/dispatcher.py", line 201, in _dispatch
    result = rpc.result(meth(_c_args, *_c_kwargs))
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/wizard/wizard.py", line 275, in execute
    return wizard._execute(state_name)
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/wizard/wizard.py", line 306, in _execute
    result = self._execute(transition())
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/ir/module.py", line 570, in transition_upgrade
    pool.init(update=update, lang=lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/pool.py", line 155, in init
    lang=lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/modules/__init__.py", line 434, in load_modules
    _load_modules()
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/modules/__init__.py", line 398, in _load_modules
    load_module_graph(graph, pool, update, lang)
  File "/usr/local/lib/python2.7/dist-packages/trytond-4.0.4-py2.7.egg/trytond/modules/__init__.py", line 237, in load_module_graph
    cls.**register**(module)
  File "/usr/local/lib/python2.7/dist-packages/trytonar_party_ar-4.0.0-py2.7.egg/trytond/modules/party_ar/party.py", line 349, in **register**
    where=(sql_table.type == 'ar_foreign')))
ProgrammingError: column a.vat_country does not exist
LINE 1: SELECT "a"."id", "a"."vat_country", "a"."country" FROM "part...

**Comment by s4msagaz** [comment]
Estimados, he modificado esa linea, cambiando

        # Migrate to 4.0
        cursor.execute(*sql_table.select(
                sql_table.id, sql_table.vat_country, sql_table.country,
        where=(sql_table.type == 'ar_foreign')))

por

        # Migrate to 4.0
        cursor.execute(*sql_table.select(
                sql_table.id, sql_table.country,
        where=(sql_table.type == 'ar_foreign')))

y salió andando con fritas!, el tema es q no se que funcionalidad he quitado :D

La linea en cuestión es la 352

**Comment by lukio** [comment]
This commited 6c3da171 fixed this issue.
