### ISSUE TITLE
AttributeError: module 'trytond.backend' has no attribute 'get'

### ISSUE THREAD

**Issue by cburgosster** [tryton-ar/party_ar#23]
error AttributeError: module 'trytond.backend' has no attribute 'get' al intentar actualizar modulos instalados  account_ar account_invoice_ar bank_ar y party_ar  party_ar response  AttributeError: module 'trytond.backend' has no attribute 'get' en tryton 5.6 (se trata de un error en la librería o en la intregracion con pyafipsws?)

 y en el cliente crashea con el sig: ERROR trytond.protocols.dispatcher <class 'trytond.ir.module.Module'>.activate(*([18], {'client': '683f5a96-2ffc-4630-9661-c3df2de8677e', 'warehouse': None, 'employee': None, 'company': 1, 'company.rec_name': 'Coopevic Ltda', 'language': 'es', 'language_direction': 'ltr', 'groups': [1, 7, 9, 2, 8, 3, 13, 5, 4, 6, 11, 10, 12], '_timestamp': {'ir.module,18': '1597358996.97072'}}), **{}) from admin@127.0.0.1//tryton_test/
Traceback (most recent call last):
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/protocols/dispatcher.py", line 181, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelview.py", line 725, in wrapper
    return func(cls, records, *args, **kwargs)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 39, in wrapper
    return func(cls, modules)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 216, in activate
    modules_activated.update((m for m in get_parents(module)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 212, in get_parents
    parents.update(get_parents(p))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 212, in get_parents
    parents.update(get_parents(p))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 212, in get_parents
    parents.update(get_parents(p))
  [Previous line repeated 900 more times]
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 210, in get_parents
    parents = set(p for p in module.parents)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/function.py", line 130, in __get__
    return super().__get__(inst, cls)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/field.py", line 336, in __get__
    return inst.__getattr__(self.name)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelstorage.py", line 1560, in __getattr__
    read_data = self.read(list(ids), list(ffields.keys()))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelsql.py", line 839, in read
    getter_results = field.get(ids, cls, field_list, values=result)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/function.py", line 106, in get
    return dict((name, call(name)) for name in names)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/function.py", line 106, in <genexpr>
    return dict((name, call(name)) for name in names)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/function.py", line 99, in call
    return method(records, name)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 148, in get_parents
    parent_names = list(set(d.name for m in modules
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/ir/module.py", line 149, in <genexpr>
    for d in m.dependencies))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/field.py", line 336, in __get__
    return inst.__getattr__(self.name)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelstorage.py", line 1560, in __getattr__
    read_data = self.read(list(ids), list(ffields.keys()))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelsql.py", line 820, in read
    getter_result = field.get(ids, cls, fname, values=result)
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/fields/one2many.py", line 138, in get
    targets.append(Target.search(clause, order=self.order))
  File "/home/usuario/.local/lib/python3.6/site-packages/trytond/model/modelsql.py", line 1317, in search
    cursor.execute(*select)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 194, in __iter__
    yield str(self)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 579, in __str__
    columns = ', '.join(map(self._format_column, self.columns))
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 500, in _format_column
    return '%s AS %s' % (expression, column)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 1365, in __str__
    return 'CAST(%s AS %s)' % (value, self.typename)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/functions.py", line 112, in __str__
    + ')')
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/functions.py", line 74, in _format
    return str(value)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/conditionals.py", line 94, in __str__
    + '(' + ', '.join(map(self._format, self.values)) + ')')
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/conditionals.py", line 43, in _format
    return str(value)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 1324, in __str__
    alias = self._from.alias
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 251, in alias
    return AliasManager.get(self)
  File "/home/usuario/.local/lib/python3.6/site-packages/sql/__init__.py", line 156, in get
    if getattr(cls.local, 'alias', None) is None:
RecursionError: maximum recursion depth exceeded in comparison
4488 140416439547648 [2020-08-14 20:50:42,673] INFO werkzeug 127.0.0.1 - - [14/Aug/2020 20:50:42] "POST /tryton_test/ HTTP/1.1" 200 -

**Comment by lukio** [comment]
Hola @cburgosster los módulos de la localización argentina están probadas y testeadas hasta la versión 5.2 de trytond.
Si deseas realizar una instalación de la versión 5.6, debes adecuar los módulos de la localización hasta esa versión.
¡Los parches para son bienvenidos!

**Comment by lukio** [comment]
Cierro ticket. Los módulos fueron migrados y testeados hasta la versión 6.6.
